language: csharp
solution: kin-base-csharp.sln

mono: none

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows

dotnet: 2.2.401

script:
  - make test

notifications:
  email: false
