language: csharp
solution: kin-base-csharp.sln

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows

dotnet: 2.2

script:
  - make test

notifications:
  email: false
